#!/bin/sh -x

# Specify a new 'root' password for MariaDB

if [ "$MYSQL_ROOT_PASSWORD" = "" ];
  then
    echo "You must provide a MYSQL_ROOT_PASSWORD"
    echo "Current password is 'INSecure' and your MariaDB installation will be"
    echo " insecure untill you provide a password during startup as shown below"
    echo " sudo docker run -e "MYSQL_ROOT_PASSWORD=yourpw" broadtech/alpine-mariadb"
    echo "If you have already set a password ignore this warning"

  else
    echo "Changing password for root user"
     /usr/bin/mysqld --user=root & \
    sleep 20s \
    && echo "GRANT ALL ON *.* TO root@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD' \
             WITH GRANT OPTION; FLUSH PRIVILEGES;" | mysql -u root -pINSecure \
    && echo "GRANT ALL ON *.* TO root@'%' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD' \
             WITH GRANT OPTION; FLUSH PRIVILEGES;" | mysql -u root -p$MYSQL_ROOT_PASSWORD \
    && sleep 20s \
    && /usr/bin/mysqladmin -u root -p$MYSQL_ROOT_PASSWORD shutdown \
    && sleep 10s \
    && /usr/bin/mysqld --user=root

fi
